runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  operating_system: ubuntu22
  runtime_version: "3.10"


manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: .5
  disk_size_gb: 10
